services:
  hopp-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: hopp-server
    environment:
      - PORT=4077
      - MAX_PAYLOAD_MB=15
    volumes:
      - ./server/data:/app/data
    restart: unless-stopped

  hopp-web:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: hopp-web
    depends_on:
      - hopp-server
    restart: unless-stopped
